version: '2'

services:
  derby:
    build: .
    container_name: derby645
    image: pinewoodderby
    command: sleep infinity
    environment:
      - DJANGO_SETTINGS_MODULE=derby.settings.docker
    volumes:
      - /home/dave/Projects/PinewoodDerbyData:/data
